name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Do not enable pnpm cache here; pnpm isn't on PATH yet at this step

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          GITHUB_ACTIONS: "true"
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: pnpm build

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Configure GitHub Pages (best effort)
        uses: actions/configure-pages@v5
        continue-on-error: true
        with:
          enablement: true

      - name: Ensure Pages site exists (optional via PAT)
        if: ${{ secrets.GH_PAT_PAGES != '' }}
        env:
          GH_PAT_PAGES: ${{ secrets.GH_PAT_PAGES }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          echo "Checking if Pages site exists..."
          status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${GH_PAT_PAGES}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/pages")
          if [ "$status" = "404" ]; then
            echo "Creating Pages site via REST API..."
            curl -sfL -X POST \
              -H "Authorization: token ${GH_PAT_PAGES}" \
              -H "Accept: application/vnd.github+json" \
              -d '{"build_type":"workflow"}' \
              "https://api.github.com/repos/${REPO}/pages"
          else
            echo "Pages site already exists (status ${status})."
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
